
    - name: Add user to user groups
      user: name={{ansible_user_id}} groups={{ item }} append=yes
      with_items:
      - docker
      - pcp
      become: yes

    - name: Get nodejs setup script
      get_url: url=https://deb.nodesource.com/setup_6.x dest=~/nodejs-installer
      become: yes

    - name: Setup nodejs
      command: /bin/bash ~/nodejs-installer
      become: yes

    - name: Install nodejs
      apt: pkg=nodejs
      become: yes

    - name: Install global NPM packages
      npm: name={{ item.name }} version={{ item.version }} global=yes
      become: yes
      with_items:
      - {name: grunt-cli, version: 1.2.0}

    - name: Install vim-javascript
      git: repo=https://github.com/pangloss/vim-javascript.git dest=~/.vim/bundle/vim-javascript
