    - name: Determine if laptop
      command: laptop-detect
      register: is_laptop
      ignore_errors: yes

    - name: Determine if nVidia graphics card
      shell: hwinfo --gfxcard | fgrep "Model:" | fgrep -i nvidia
      register: is_nvidia
      ignore_errors: yes

    - name: Create home directories
      file: path=~/{{ item }} state=directory
      with_items:
      - Installs
      - .config/terminator

    - name: Symlink ~/Installs
      file: src=~/Installs dest=/tmp/Installs state=link

    - name: Install base packages
      apt: pkg={{ item }}
      become: yes
      with_items:
      - build-essential
      - libssl-dev
      - libffi-dev
      - python-dev
      - python-pip
      - python-software-properties
      - python-gpgme

    - name: Remove Totem media player
      apt: pkg=totem state=absent
      become: yes

    - name: Install VLC media player
      apt: pkg=vlc
      become: yes

    - name: Install gnote note taking application
      apt: pkg=gnote
      become: yes

    - name: Install Address Book
      apt: pkg=address-book-app
      become: yes

    - name: Install Geary email client
      apt: pkg=geary
      become: yes

    - name: Install chromium web browser
      apt: pkg=chromium-browser
      become: yes

    - name: Install git source control
      apt: pkg=git-core
      become: yes

    - name: Install gitg git GUI
      apt: pkg=gitg
      become: yes

    - name: Set vim as git editor
      git_config: name=core.editor scope=global value=vim

    - name: Install subversion source control
      apt: pkg=subversion
      become: yes

    - name: Install ansible configuration management
      pip: name=ansible version=2.1.1.0
      become: yes

    - name: Install terminator terminal emulator
      apt: pkg=terminator
      become: yes

    - name: Copy terminator configuration
      copy: src=terminator.config dest=~/.config/terminator/config

    - name: Install HTTPie cURL wrapper
      apt: pkg=httpie
      become: yes

    - name: Install tmux terminal multiplexer
      apt: pkg=tmux
      become: yes

    - name: Install icdiff side by side diff tool
      pip: name=icdiff
      become: yes

    - name: Install SSH server
      apt: pkg=openssh-server
      become: yes

    - name: Install OpenVPN client
      apt: pkg=openvpn
      become: yes

    - name: Install rbenv ruby version control
      apt: pkg={{ item }}
      become: yes
      with_items:
      - rbenv
      - ruby-build

    - name: Add user to user groups
      user: name={{ansible_user_id}} groups={{ item }} append=yes
      with_items:
      - docker
      - pcp
      become: yes

    - name: Install vim plugins
      git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.dest }}
      with_items:
      - {repo: "https://github.com/pearofducks/ansible-vim.git", dest: ansible-vim}
      - {repo: "https://github.com/plasticboy/vim-markdown.git", dest: vim-markdown}

    - name: Update vim configuration
      lineinfile: dest=~/.vimrc line="{{ item }}"
      with_items:
      - let g:vim_markdown_folding_style_pythonic = 1

    - name: Download .deb
      get_url: url={{ item.url }} dest=~/Installs/{{ item.name }}
      with_items: "{{ installs }}"

    - name: Install .deb
      apt: deb=/tmp/Installs/{{ item.name }}
      become: yes
      with_items: "{{ installs }}"

    - name: Get JetBrains toolbox
      get_url: url=https://download-cf.jetbrains.com/toolbox/jetbrains-toolbox-1.1.2143.tar.gz dest=~/Installs/jetbrains-toolbox-1.1.2143.tar.gz

    - name: Extract JetBrains toolbox
      unarchive: src=~/Installs/jetbrains-toolbox-1.1.2143.tar.gz dest=/tmp

    - name: Copy JetBrains toolbox
      copy: src=/tmp/jetbrains-toolbox-1.1.2143/jetbrains-toolbox dest=/usr/bin/jetbrains-toolbox mode=0755
      become: yes

    - name: Install GIMP photo editor
      apt: pkg=gimp
      become: yes

    - name: Install shutter screenshot tool
      apt: pkg=shutter
      become: yes

    - name: Install PlantUML diagramming tool
      apt: pkg=plantuml
      become: yes

    - name: Copy bashrc source file
      copy: src=bashrc dest=/tmp/bashrc

    - name: Get .bashrc content 
      shell: cat /tmp/bashrc
      register: bashrc_content

    - name: Update .bashrc 
      blockinfile:
        dest: ~/.bashrc
        backup: yes
        block: |
          {{ bashrc_content.stdout }}

    - name: Add rbenv to .bashrc
      lineinfile: dest=~/.bashrc line='eval "$(rbenv init -)"'

    - name: Install Laptop Mode Tools
      apt: pkg=laptop-mode-tools
      when: is_laptop|succeeded
      become: yes

    - name: Install multitouch gesture recognizer
      apt: pkg=touchegg
      when: is_laptop|succeeded
      become: yes

    - name: Copy touchegg configuration
      copy: src={{ item.source }} dest={{ item.destination }}
      when: is_laptop|succeeded
      with_items:
      - {source: touchegg.conf, destination: ~/.config/touchegg/touchegg.conf}
      - {source: xprofile, destination: ~/.xprofile}

    - name: Install nVidia drivers for laptop
      apt: pkg=nvidia-current
      when: is_nvidia and is_laptop|succeeded
      become: yes
