    - name: Install chromium-browser
      apt: pkg=chromium-browser
      become: yes

    - name: Install terminator
      apt: pkg=terminator
      become: yes

    - name: Install rbenv
      apt: pkg={{ item }}
      become: yes
      with_items:
      - rbenv
      - ruby-build

    - name: Add user to user groups
      user: name={{ansible_user_id}} groups={{ item }} append=yes
      with_items:
      - docker
      - pcp
      become: yes

    - name: Get nodejs setup script
      get_url: url=https://deb.nodesource.com/setup_6.x dest=~/nodejs-installer
      become: yes

    - name: Setup nodejs
      command: /bin/bash ~/nodejs-installer
      become: yes

    - name: Install nodejs
      apt: pkg=nodejs
      become: yes

    - name: Install global NPM packages
      npm: name={{ item.name }} version={{ item.version }} global=yes
      become: yes
      with_items:
      - {name: grunt-cli, version: 1.2.0}

    - name: Install vim-javascript
      git: repo=https://github.com/pangloss/vim-javascript.git dest=~/.vim/bundle/vim-javascript

    - name: Create home directories
      file: path=~/{{ item }} state=directory
      with_items:
      - Installs

    - name: Download .deb
      get_url: url={{ item.url }} dest=~/Installs/{{ item.name }}
      with_items:
      - {url: "http://download.virtualbox.org/virtualbox/5.1.14/virtualbox-5.1_5.1.14-112924~Ubuntu~xenial_amd64.deb", name: virtualbox-5.1_5.1.14-112924~Ubuntu~xenial_amd64.deb}
      - {url: "https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb", name: vagrant_1.9.1_x86_64.deb}

    - name: Symlink ~/Installs
      file: src=~/Installs dest=/tmp/Installs state=link

    - name: Install .deb
      apt: deb=/tmp/Installs/{{ item }}
      become: yes
      with_items:
      - virtualbox-5.1_5.1.14-112924~Ubuntu~xenial_amd64.deb
      - vagrant_1.9.1_x86_64.deb

    - name: Copy bashrc source file
      copy: src=bashrc dest=/tmp/bashrc

    - name: Get .bashrc content 
      shell: cat /tmp/bashrc
      register: bashrc_content

    - name: Update .bashrc 
      blockinfile:
        dest: ~/.bashrc
        backup: yes
        block: |
          {{ bashrc_content.stdout }}
